import {
  sensorById,
  buildBom,
  WIRING_CHECKLIST,
  FIRMWARE_NOTES,
  TROUBLESHOOTING,
  MQ_ADC1_PINS,
  I2C_PINS,
  ENCLOSURE_SPECS,
  REPO_LINKS,
  CONTROLLERS,
  SAFETY_NOTES,
  COMMON_MISTAKES,
  TIPS,
  BREADBOARD_GUIDE,
} from "@/lib/e-nose/data"
import type { PlanInput } from "@/lib/e-nose/data"

const PAGE_W = 210
const PAGE_H = 297
const M = 14
const BOTTOM = PAGE_H - M

const CP1252_SPECIAL = new Set([
  0x20ac, 0x2013, 0x2014, 0x2018, 0x2019, 0x201a, 0x201c, 0x201d, 0x201e, 0x2020, 0x2021,
  0x2022, 0x2026, 0x2030, 0x2039, 0x203a, 0x02c6, 0x02dc, 0x0152, 0x0153, 0x0160, 0x0161,
  0x0178, 0x017d, 0x017e, 0x0192, 0x2122,
])
const REPLACEMENTS: [RegExp, string][] = [
  [/→/g, "->"],
  [/Ω/g, "ohm"],
  [/≈/g, "~"],
  [/≥/g, ">="],
  [/≤/g, "<="],
  [/±/g, "+/-"],
  [/✓/g, "yes"],
  [/₀/g, "0"],
  [/₁/g, "1"],
  [/₂/g, "2"],
  [/₃/g, "3"],
  [/₄/g, "4"],
  [/₅/g, "5"],
  [/₆/g, "6"],
  [/₇/g, "7"],
  [/₈/g, "8"],
  [/₉/g, "9"],
]
const CP1252_UNASSIGNED = new Set([0x81, 0x8d, 0x8f, 0x90, 0x9d])

function sanitize(text: string): string {
  let out = text
  for (const [re, sub] of REPLACEMENTS) out = out.replace(re, sub)
  let result = ""
  for (const ch of out) {
    const cp = ch.codePointAt(0)!
    if ((cp <= 0xff && !CP1252_UNASSIGNED.has(cp)) || CP1252_SPECIAL.has(cp)) {
      result += ch
    } else {
      result += "?"
    }
  }
  return result
}

let y = 0
let doc: any = null

function ensure(needed: number) {
  if (y + needed > BOTTOM) {
    doc.addPage()
    y = M
  }
}

function rule() {
  doc.setDrawColor(0)
  doc.setLineWidth(0.3)
  doc.line(M, y, PAGE_W - M, y)
  y += 4
}

function heading(text: string) {
  text = sanitize(text)
  ensure(16)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(12)
  doc.text(text.toUpperCase(), M, y)
  y += 2
  rule()
}

function para(text: string, size = 9, opts?: { bold?: boolean }) {
  text = sanitize(text)
  doc.setFont("helvetica", opts?.bold ? "bold" : "normal")
  doc.setFontSize(size)
  const lines = doc.splitTextToSize(text, PAGE_W - M * 2)
  for (const ln of lines) {
    ensure(5)
    doc.text(ln, M, y)
    y += 4.6
  }
  y += 1.5
}

function bullet(text: string) {
  text = sanitize(text)
  const lines = doc.splitTextToSize(text, PAGE_W - M * 2 - 6)
  lines.forEach((ln: string, i: number) => {
    ensure(5)
    doc.text(i === 0 ? "•  " + ln : "   " + ln, M, y)
    y += 4.6
  })
  y += 1
}

interface TableCol {
  title: string
  width: number
}

function table(cols: TableCol[], rows: (string[] | string)[][]) {
  cols = cols.map((c) => ({ ...c, title: sanitize(c.title) }))
  rows = rows.map((row) =>
    row.map((cell) => (typeof cell === "string" ? sanitize(cell) : cell.map(sanitize))),
  )
  const colX: number[] = []
  let x = M
  cols.forEach((c) => {
    colX.push(x)
    x += c.width
  })
  const cellPad = 1.6
  const rowH = (rows: (string | string[])[]) => {
    let max = 1
    rows.forEach((cell, i) => {
      const w = cols[i].width - cellPad * 2
      const n = doc.splitTextToSize(cell, w).length
      max = Math.max(max, n)
    })
    return max * 4.2 + 3.2
  }
  const headerH = 7
  ensure(headerH + 4)
  cols.forEach((c, i) => {
    doc.setFont("helvetica", "bold")
    doc.setFontSize(8)
    doc.rect(colX[i], y, c.width, headerH)
    doc.text(c.title, colX[i] + cellPad, y + 4.8)
  })
  y += headerH
  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  for (const row of rows) {
    const h = rowH(row)
    ensure(h)
    let rowLines: string[][] = []
    row.forEach((cell, i) => {
      const w = cols[i].width - cellPad * 2
      rowLines.push(doc.splitTextToSize(cell, w))
    })
    row.forEach((_, i) => {
      doc.rect(colX[i], y, cols[i].width, h)
      rowLines[i].forEach((ln: string, j: number) => {
        doc.text(ln, colX[i] + cellPad, y + 3.6 + j * 4.2)
      })
    })
    y += h
  }
  y += 3
}

async function createDoc(input: PlanInput): Promise<any> {
  ;({ doc } = await import("jspdf").then((m) => ({ doc: new m.jsPDF({ unit: "mm", format: "a4" }) })))
  y = M

  const sensors = input.sensors.map(sensorById).filter(Boolean) as NonNullable<ReturnType<typeof sensorById>>[]
  const mqCount = sensors.filter((s) => s.kind === "mox-analog").length
  const digital = sensors.filter((s) => s.kind === "mox-digital")
  const hasDigital = digital.length > 0
  const bom = buildBom(input)

  doc.setFont("helvetica", "bold")
  doc.setFontSize(20)
  doc.text("OpenSmell · E-Nose Build Plan", M, y + 6)
  y += 12

  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  const summary = `${input.goal} — ${sensors.length} sensor${sensors.length > 1 ? "s" : ""}`
  para(summary, 10, { bold: true })
  para("Generated by the OpenSmell builder. Every part, pin, and step is sourced from the open electronic-nose reference build — verify against the repo before you order.", 8)
  y += 2

  heading("Sensors")
  table(
    [
      { title: "Sensor", width: 34 },
      { title: "Detects", width: 60 },
      { title: "Interface", width: 30 },
      { title: "Support", width: 58 },
    ],
    sensors.map((s) => [s.name, s.target, s.io, s.support === "full" ? "Full — in the standard kit" : s.support === "partial" ? "Hardware-ready · DIY firmware" : "Needs extra hardware"]),
  )

  heading("Controllers")
  table(
    [
      { title: "Board", width: 42 },
      { title: "ADC inputs", width: 46 },
      { title: "Wireless", width: 34 },
      { title: "Fit", width: 60 },
    ],
    CONTROLLERS.map((c) => [c.name, c.adc, c.wireless, c.fit]),
  )
  para("The ESP32 is the recommended board — Osmograph flashes it one-click and its ADC1 pins are WiFi-safe. Other controllers work if you already own one: they share the same CSV stream contract, but need pin remaps, fewer channels, or a USB-only host. See the notes above before ordering parts.", 8)

  heading("Bill of materials")
  table(
    [
      { title: "Item", width: 78 },
      { title: "Qty", width: 14 },
      { title: "Purpose", width: 90 },
    ],
    bom.map((b) => [b.item, b.qty, b.purpose]),
  )
  para(`Prices are intentionally not listed — they vary by region. Source locally where possible. Two 10 kΩ resistors are needed per MQ sensor for the voltage divider. ${BREADBOARD_GUIDE.footprint}`, 8)

  heading("Wiring")
  if (mqCount > 0) {
    para("Each MQ sensor connects to a unique ADC1 GPIO. ADC1 is WiFi-safe on the ESP32 (avoid ADC2 pins 25/26 when recording over WiFi).", 8.5)
    table(
      [
        { title: "MQ sensor", width: 40 },
        { title: "GPIO (ADC1)", width: 40 },
        { title: "Notes", width: 102 },
      ],
      sensors
        .filter((s) => s.kind === "mox-analog")
        .map((s, i) => [s.name, MQ_ADC1_PINS[i] ?? "—", "AO → two equal 10 kΩ resistors → GPIO (half-voltage divider)" + (i === 0 ? "; VCC → 5 V rail; GND → common ground; DO ignored" : "")]),
    )
  }
  if (hasDigital) {
    para(
      `Digital sensors join the I²C bus: VDD → 3.3 V, GND → common ground, SDA → ${I2C_PINS.sda}, SCL → ${I2C_PINS.scl}. They do not need a voltage divider.`,
      8.5,
    )
  }

  heading("Wiring checklist")
  WIRING_CHECKLIST.forEach(bullet)

  heading("Before you power up — safety")
  SAFETY_NOTES.forEach(bullet)

  heading("Common mistakes")
  COMMON_MISTAKES.forEach(([m, f]) => {
    bullet(`${m} — ${f}`)
  })

  heading("Firmware")
  para(hasDigital ? FIRMWARE_NOTES.withDigital : FIRMWARE_NOTES.mqOnly, 9)
  para(FIRMWARE_NOTES.stream, 8)

  heading("Burn-in & first test")
  bullet("New metal-oxide sensors need ~24 cumulative hours powered on before readings stabilise. The clock does not reset if power is interrupted.")
  bullet("Before every recording session, let the sensors warm up for 5 minutes.")
  bullet("Flash the firmware, open the serial monitor at 115200 baud, and confirm comma-separated numbers stream steadily.")
  bullet("Crush a clove of garlic, bring it near the array — the numbers should rise or fall clearly, then drift back over 30–60 seconds.")

  heading("After flashing — tips")
  TIPS.forEach(bullet)

  heading("Calibration")
  para(
    "The OpenSmell calibration pipeline translates a new device's voltages into the shared representation OpenSmell apps understand. The Osmograph Calibration Wizard is under active development. Within-session experiments work now: record one substance, record another, and compare the sensor traces and latent vectors.",
    8.5,
  )

  heading("Enclosure")
  bullet(ENCLOSURE_SPECS.summary)
  bullet(ENCLOSURE_SPECS.base)
  bullet(ENCLOSURE_SPECS.lid)
  bullet(ENCLOSURE_SPECS.clearance)
  bullet(ENCLOSURE_SPECS.airflow)

  heading("Troubleshooting")
  table(
    [
      { title: "Symptom", width: 52 },
      { title: "Likely cause", width: 52 },
      { title: "Fix", width: 78 },
    ],
    TROUBLESHOOTING,
  )

  heading("Before you build")
  para(
    "Cross-check every connection against this plan before applying power. This is open-source documentation maintained by hand and by community fixes — wiring, pin numbers, and part behaviour can vary between boards and sensor clones. If something looks wrong, check the electronic-nose repo and the community before trusting it. Start with one sensor, prove it works, then grow the array.",
    8.5,
  )

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  para("Sources: electronic-nose reference repo (BOM, WIRING, BUILD, ENCLOSURE, EXPERIMENT). Calibration and digital-sensor software are under active development — treat those capabilities as in-progress, not finished. This plan is provided as-is; verify before you order or power anything.", 8)

  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(7.5)
    doc.text("OpenSmell · open hardware / open data / open software", M, PAGE_H - 8)
    doc.text(`Page ${i} of ${pages} · ${REPO_LINKS.repo}`, PAGE_W - M, PAGE_H - 8, { align: "right" })
  }

  return doc
}

export async function buildPlanBlob(input: PlanInput): Promise<Blob> {
  const d = await createDoc(input)
  return d.output("blob")
}

export async function buildPlanPdf(input: PlanInput): Promise<void> {
  const d = await createDoc(input)
  const stamp = new Date().toISOString().slice(0, 10)
  d.save(`opensmell-enose-build-plan-${stamp}.pdf`)
}
